version: '3'

services:
  app:
    build:
      context: .   # Use the current directory as the build context
    ports:
      - "8085:8085"  # Map your application's port to the host machine
    depends_on:
      - db  # Ensure the app starts after the database
      - redis  # Ensure the app starts after the Redis service

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"  # Map MySQL port to the host machine
    volumes:
      - mysql_data:/var/lib/mysql  # Mount a volume for persistent MySQL data storage

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Map Redis port to the host machine
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    volumes: 
      - cache:/data
    command: redis-server

volumes:
  mysql_data:
  cache:
      driver: local
